web:
  build: .
  command: bash -c "mvn clean resources:resources liquibase:update && ./runserver.sh"
  volumes:
    - ./root
  ports:
    - 8080:8080
  links:
    - db
db:
  build: ./src/main/resources/dbschema
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_DB=InovaDB
  expose:
    - "5432"
  volumes:
  - ./postgres-data:/var/lib/postgresql/data